### ISSUE TITLE
new build release？

### ISSUE THREAD

**Issue by ygd2013520** [seer-robotics/SeerTCPTest#2]
你好，请问可以将最新的源码编译成可执行文件release出来吗？看到你们最新的release还是2017年的，之前release版本打开和readme的说明不一致

**Comment by ye-ys** [comment]
> 你好，请问可以将最新的源码编译成可执行文件release出来吗？看到你们最新的release还是2017年的，之前release版本打开和readme的说明不一致

好的，周一提供（2021.1.11）

**Comment by ygd2013520** [comment]
好的，感谢

**Comment by ye-ys** [comment]
已经 Release。https://github.com/seer-robotics/SeerTCPTest/releases/tag/0.4.0

**Comment by ygd2013520** [comment]
好的
